# Generated by Django 3.0.7 on 2022-12-25 01:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=100)),
                ('asstes_name', models.CharField(max_length=100)),
                ('request_by', models.PositiveIntegerField()),
                ('request_accepted_by', models.PositiveIntegerField()),
                ('request_reason', models.CharField(max_length=100)),
                ('is_free', models.BooleanField(default=True)),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
                ('image', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
    ]
