# Generated by Django 3.0.7 on 2022-12-25 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20221225_0755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assets',
            old_name='asstes_name',
            new_name='assets_name',
        ),
    ]
