# Generated by Django 3.0.7 on 2022-12-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20221225_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='request_accepted_by',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='assets',
            name='request_by',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
